theme: jekyll-theme-tactile
# Site settings
title: "Spindle - Asuwada Mode"

 
 description: "A tool for participatory networked storytelling games."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Dr. Tabea Hirzel"
resume_title:                   "Spindle - Asuwada Mode"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "spindle.game@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "663 093 944"
resume_contact_address:         "Tomelloso - Spain"

resume_header_contact_info:     "Spain, Tomelloso • 13700 • spindle.game@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>The Spindle is a PHP MYSQL application that serves to play collaborative networked storytelling games based on historiographic data. It was originally developed as a prototype in the course of the research Principles of Liberty by Dr. Tabea Hirzel. There are different modes of playing this game, all included in the diferent releases of Spindle.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/spindle-asuwada/"
  resume_twitter_url:           "http://twitter.com/spindle-asuwada"
  resume_dribbble_url:          "https://dribbble.com/spindle-asuwada"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/spindle-asuwada"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://spindlegames.blogspot.com"
  resume_medium_url:            "https://medium.com/@spindle-asuwada"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
