<?php
// This script and data application were generated by AppGini 5.94
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/class_dictionary5.php");
	include_once("{$currDir}/class_dictionary5_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('class_dictionary5');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout(function() { window.location = "index.php?signOut=1"; }, 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = 'class_dictionary5';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`class_dictionary5`.`id`" => "id",
		"IF(    CHAR_LENGTH(`class_dictionary11`.`category`), CONCAT_WS('',   `class_dictionary11`.`category`), '') /* Class1 */" => "class1",
		"IF(    CHAR_LENGTH(`class_dictionary21`.`category`), CONCAT_WS('',   `class_dictionary21`.`category`), '') /* Class2 */" => "class2",
		"IF(    CHAR_LENGTH(`class_dictionary31`.`category`), CONCAT_WS('',   `class_dictionary31`.`category`), '') /* Class3 */" => "class3",
		"IF(    CHAR_LENGTH(`class_dictionary41`.`category`), CONCAT_WS('',   `class_dictionary41`.`category`), '') /* Class4 */" => "class4",
		"`class_dictionary5`.`category`" => "category",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`class_dictionary5`.`id`',
		2 => '`class_dictionary11`.`category`',
		3 => '`class_dictionary21`.`category`',
		4 => '`class_dictionary31`.`category`',
		5 => '`class_dictionary41`.`category`',
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`class_dictionary5`.`id`" => "id",
		"IF(    CHAR_LENGTH(`class_dictionary11`.`category`), CONCAT_WS('',   `class_dictionary11`.`category`), '') /* Class1 */" => "class1",
		"IF(    CHAR_LENGTH(`class_dictionary21`.`category`), CONCAT_WS('',   `class_dictionary21`.`category`), '') /* Class2 */" => "class2",
		"IF(    CHAR_LENGTH(`class_dictionary31`.`category`), CONCAT_WS('',   `class_dictionary31`.`category`), '') /* Class3 */" => "class3",
		"IF(    CHAR_LENGTH(`class_dictionary41`.`category`), CONCAT_WS('',   `class_dictionary41`.`category`), '') /* Class4 */" => "class4",
		"`class_dictionary5`.`category`" => "category",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`class_dictionary5`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`class_dictionary11`.`category`), CONCAT_WS('',   `class_dictionary11`.`category`), '') /* Class1 */" => "Class1",
		"IF(    CHAR_LENGTH(`class_dictionary21`.`category`), CONCAT_WS('',   `class_dictionary21`.`category`), '') /* Class2 */" => "Class2",
		"IF(    CHAR_LENGTH(`class_dictionary31`.`category`), CONCAT_WS('',   `class_dictionary31`.`category`), '') /* Class3 */" => "Class3",
		"IF(    CHAR_LENGTH(`class_dictionary41`.`category`), CONCAT_WS('',   `class_dictionary41`.`category`), '') /* Class4 */" => "Class4",
		"`class_dictionary5`.`category`" => "Category",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`class_dictionary5`.`id`" => "id",
		"IF(    CHAR_LENGTH(`class_dictionary11`.`category`), CONCAT_WS('',   `class_dictionary11`.`category`), '') /* Class1 */" => "class1",
		"IF(    CHAR_LENGTH(`class_dictionary21`.`category`), CONCAT_WS('',   `class_dictionary21`.`category`), '') /* Class2 */" => "class2",
		"IF(    CHAR_LENGTH(`class_dictionary31`.`category`), CONCAT_WS('',   `class_dictionary31`.`category`), '') /* Class3 */" => "class3",
		"IF(    CHAR_LENGTH(`class_dictionary41`.`category`), CONCAT_WS('',   `class_dictionary41`.`category`), '') /* Class4 */" => "class4",
		"`class_dictionary5`.`category`" => "category",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['class1' => 'Class1', 'class2' => 'Class2', 'class3' => 'Class3', 'class4' => 'Class4', ];

	$x->QueryFrom = "`class_dictionary5` LEFT JOIN `class_dictionary1` as class_dictionary11 ON `class_dictionary11`.`id`=`class_dictionary5`.`class1` LEFT JOIN `class_dictionary2` as class_dictionary21 ON `class_dictionary21`.`id`=`class_dictionary5`.`class2` LEFT JOIN `class_dictionary3` as class_dictionary31 ON `class_dictionary31`.`id`=`class_dictionary5`.`class3` LEFT JOIN `class_dictionary4` as class_dictionary41 ON `class_dictionary41`.`id`=`class_dictionary5`.`class4` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'class_dictionary5_view.php';
	$x->RedirectAfterInsert = 'class_dictionary5_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Class dictionary1';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`class_dictionary5`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Class1', 'Class2', 'Class3', 'Class4', 'Category', ];
	$x->ColFieldName = ['class1', 'class2', 'class3', 'class4', 'category', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/class_dictionary5_templateTV.html';
	$x->SelectedTemplate = 'templates/class_dictionary5_templateTVS.html';
	$x->TemplateDV = 'templates/class_dictionary5_templateDV.html';
	$x->TemplateDVP = 'templates/class_dictionary5_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `class_dictionary5`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='class_dictionary5' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `class_dictionary5`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='class_dictionary5' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`class_dictionary5`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: class_dictionary5_init
	$render = true;
	if(function_exists('class_dictionary5_init')) {
		$args = [];
		$render = class_dictionary5_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: class_dictionary5_header
	$headerCode = '';
	if(function_exists('class_dictionary5_header')) {
		$args = [];
		$headerCode = class_dictionary5_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: class_dictionary5_footer
	$footerCode = '';
	if(function_exists('class_dictionary5_footer')) {
		$args = [];
		$footerCode = class_dictionary5_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
