<?php
// This script and data application were generated by AppGini 5.94
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/hist_encounter.php");
	include_once("{$currDir}/hist_encounter_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('hist_encounter');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout(function() { window.location = "index.php?signOut=1"; }, 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = 'hist_encounter';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`hist_encounter`.`id`" => "id",
		"IF(    CHAR_LENGTH(`bio_chr1`.`id`) || CHAR_LENGTH(`bio_chr1`.`character_name`), CONCAT_WS('',   `bio_chr1`.`id`, '   ', `bio_chr1`.`character_name`), '') /* Author A */" => "bio_chrA",
		"IF(    CHAR_LENGTH(`bio_story1`.`id`) || CHAR_LENGTH(`bio_story1`.`story_title`), CONCAT_WS('',   `bio_story1`.`id`, '   ', `bio_story1`.`story_title`), '') /* Bibliography A */" => "bio_storyA",
		"IF(    CHAR_LENGTH(`bio_storyline1`.`id`) || CHAR_LENGTH(`bio_storyline1`.`storyline_title`), CONCAT_WS('',   `bio_storyline1`.`id`, '    ', `bio_storyline1`.`storyline_title`), '') /* Transcript A */" => "bio_storyline",
		"IF(    CHAR_LENGTH(`bio_storyline2`.`storyline`), CONCAT_WS('',   `bio_storyline2`.`storyline`, '   '), '') /* Token A */" => "bio_storytext",
		"IF(    CHAR_LENGTH(`hist_chr_scene1`.`id`), CONCAT_WS('',   `hist_chr_scene1`.`id`, '   '), '') /* Scene A */" => "sceneA",
		"IF(    CHAR_LENGTH(`bio_chr2`.`id`) || CHAR_LENGTH(`bio_chr2`.`character_name`), CONCAT_WS('',   `bio_chr2`.`id`, '   ', `bio_chr2`.`character_name`), '') /* Author B */" => "bio_chrB",
		"IF(    CHAR_LENGTH(`bio_story2`.`id`) || CHAR_LENGTH(`bio_story2`.`story_title`), CONCAT_WS('',   `bio_story2`.`id`, ' -  ', `bio_story2`.`story_title`), '') /* Author name B */" => "bio_storyB",
		"IF(    CHAR_LENGTH(`bio_storyline3`.`storyline_no`) || CHAR_LENGTH(`bio_storyline3`.`storyline_title`), CONCAT_WS('',   `bio_storyline3`.`storyline_no`, '   ', `bio_storyline3`.`storyline_title`), '') /* Bibliography B */" => "bio_storylineB",
		"IF(    CHAR_LENGTH(`bio_storyline4`.`storyline`), CONCAT_WS('',   `bio_storyline4`.`storyline`, '   '), '') /* Transcript B */" => "bio_storytextB",
		"`hist_encounter`.`type`" => "type",
		"`hist_encounter`.`conflicttype`" => "conflicttype",
		"`hist_encounter`.`story_scene`" => "story_scene",
		"`hist_encounter`.`nd_color`" => "nd_color",
		"`hist_encounter`.`nd_width`" => "nd_width",
		"`hist_encounter`.`nd_style`" => "nd_style",
		"`hist_encounter`.`nd_opacity`" => "nd_opacity",
		"`hist_encounter`.`nd_visibility`" => "nd_visibility",
		"`hist_encounter`.`lbl_lable`" => "lbl_lable",
		"`hist_encounter`.`lbl_color`" => "lbl_color",
		"`hist_encounter`.`lbl_size`" => "lbl_size",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`hist_encounter`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => '`hist_encounter`.`story_scene`',
		14 => '`hist_encounter`.`nd_color`',
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`hist_encounter`.`id`" => "id",
		"IF(    CHAR_LENGTH(`bio_chr1`.`id`) || CHAR_LENGTH(`bio_chr1`.`character_name`), CONCAT_WS('',   `bio_chr1`.`id`, '   ', `bio_chr1`.`character_name`), '') /* Author A */" => "bio_chrA",
		"IF(    CHAR_LENGTH(`bio_story1`.`id`) || CHAR_LENGTH(`bio_story1`.`story_title`), CONCAT_WS('',   `bio_story1`.`id`, '   ', `bio_story1`.`story_title`), '') /* Bibliography A */" => "bio_storyA",
		"IF(    CHAR_LENGTH(`bio_storyline1`.`id`) || CHAR_LENGTH(`bio_storyline1`.`storyline_title`), CONCAT_WS('',   `bio_storyline1`.`id`, '    ', `bio_storyline1`.`storyline_title`), '') /* Transcript A */" => "bio_storyline",
		"IF(    CHAR_LENGTH(`bio_storyline2`.`storyline`), CONCAT_WS('',   `bio_storyline2`.`storyline`, '   '), '') /* Token A */" => "bio_storytext",
		"IF(    CHAR_LENGTH(`hist_chr_scene1`.`id`), CONCAT_WS('',   `hist_chr_scene1`.`id`, '   '), '') /* Scene A */" => "sceneA",
		"IF(    CHAR_LENGTH(`bio_chr2`.`id`) || CHAR_LENGTH(`bio_chr2`.`character_name`), CONCAT_WS('',   `bio_chr2`.`id`, '   ', `bio_chr2`.`character_name`), '') /* Author B */" => "bio_chrB",
		"IF(    CHAR_LENGTH(`bio_story2`.`id`) || CHAR_LENGTH(`bio_story2`.`story_title`), CONCAT_WS('',   `bio_story2`.`id`, ' -  ', `bio_story2`.`story_title`), '') /* Author name B */" => "bio_storyB",
		"IF(    CHAR_LENGTH(`bio_storyline3`.`storyline_no`) || CHAR_LENGTH(`bio_storyline3`.`storyline_title`), CONCAT_WS('',   `bio_storyline3`.`storyline_no`, '   ', `bio_storyline3`.`storyline_title`), '') /* Bibliography B */" => "bio_storylineB",
		"IF(    CHAR_LENGTH(`bio_storyline4`.`storyline`), CONCAT_WS('',   `bio_storyline4`.`storyline`, '   '), '') /* Transcript B */" => "bio_storytextB",
		"`hist_encounter`.`type`" => "type",
		"`hist_encounter`.`conflicttype`" => "conflicttype",
		"`hist_encounter`.`story_scene`" => "story_scene",
		"`hist_encounter`.`nd_color`" => "nd_color",
		"`hist_encounter`.`nd_width`" => "nd_width",
		"`hist_encounter`.`nd_style`" => "nd_style",
		"`hist_encounter`.`nd_opacity`" => "nd_opacity",
		"`hist_encounter`.`nd_visibility`" => "nd_visibility",
		"`hist_encounter`.`lbl_lable`" => "lbl_lable",
		"`hist_encounter`.`lbl_color`" => "lbl_color",
		"`hist_encounter`.`lbl_size`" => "lbl_size",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`hist_encounter`.`id`" => "Id",
		"IF(    CHAR_LENGTH(`bio_chr1`.`id`) || CHAR_LENGTH(`bio_chr1`.`character_name`), CONCAT_WS('',   `bio_chr1`.`id`, '   ', `bio_chr1`.`character_name`), '') /* Author A */" => "Author A",
		"IF(    CHAR_LENGTH(`bio_story1`.`id`) || CHAR_LENGTH(`bio_story1`.`story_title`), CONCAT_WS('',   `bio_story1`.`id`, '   ', `bio_story1`.`story_title`), '') /* Bibliography A */" => "Bibliography A",
		"IF(    CHAR_LENGTH(`bio_storyline1`.`id`) || CHAR_LENGTH(`bio_storyline1`.`storyline_title`), CONCAT_WS('',   `bio_storyline1`.`id`, '    ', `bio_storyline1`.`storyline_title`), '') /* Transcript A */" => "Transcript A",
		"IF(    CHAR_LENGTH(`bio_storyline2`.`storyline`), CONCAT_WS('',   `bio_storyline2`.`storyline`, '   '), '') /* Token A */" => "Token A",
		"IF(    CHAR_LENGTH(`hist_chr_scene1`.`id`), CONCAT_WS('',   `hist_chr_scene1`.`id`, '   '), '') /* Scene A */" => "Scene A",
		"IF(    CHAR_LENGTH(`bio_chr2`.`id`) || CHAR_LENGTH(`bio_chr2`.`character_name`), CONCAT_WS('',   `bio_chr2`.`id`, '   ', `bio_chr2`.`character_name`), '') /* Author B */" => "Author B",
		"IF(    CHAR_LENGTH(`bio_story2`.`id`) || CHAR_LENGTH(`bio_story2`.`story_title`), CONCAT_WS('',   `bio_story2`.`id`, ' -  ', `bio_story2`.`story_title`), '') /* Author name B */" => "Author name B",
		"IF(    CHAR_LENGTH(`bio_storyline3`.`storyline_no`) || CHAR_LENGTH(`bio_storyline3`.`storyline_title`), CONCAT_WS('',   `bio_storyline3`.`storyline_no`, '   ', `bio_storyline3`.`storyline_title`), '') /* Bibliography B */" => "Bibliography B",
		"IF(    CHAR_LENGTH(`bio_storyline4`.`storyline`), CONCAT_WS('',   `bio_storyline4`.`storyline`, '   '), '') /* Transcript B */" => "Transcript B",
		"`hist_encounter`.`type`" => "Type",
		"`hist_encounter`.`conflicttype`" => "Conflicttype",
		"`hist_encounter`.`story_scene`" => "Story_scene",
		"`hist_encounter`.`nd_color`" => "Nd_color",
		"`hist_encounter`.`nd_width`" => "Nd_width",
		"`hist_encounter`.`nd_style`" => "Nd_style",
		"`hist_encounter`.`nd_opacity`" => "Nd_opacity",
		"`hist_encounter`.`nd_visibility`" => "Nd_visibility",
		"`hist_encounter`.`lbl_lable`" => "Lbl_lable",
		"`hist_encounter`.`lbl_color`" => "Lbl_color",
		"`hist_encounter`.`lbl_size`" => "Lbl_size",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`hist_encounter`.`id`" => "id",
		"IF(    CHAR_LENGTH(`bio_chr1`.`id`) || CHAR_LENGTH(`bio_chr1`.`character_name`), CONCAT_WS('',   `bio_chr1`.`id`, '   ', `bio_chr1`.`character_name`), '') /* Author A */" => "bio_chrA",
		"IF(    CHAR_LENGTH(`bio_story1`.`id`) || CHAR_LENGTH(`bio_story1`.`story_title`), CONCAT_WS('',   `bio_story1`.`id`, '   ', `bio_story1`.`story_title`), '') /* Bibliography A */" => "bio_storyA",
		"IF(    CHAR_LENGTH(`bio_storyline1`.`id`) || CHAR_LENGTH(`bio_storyline1`.`storyline_title`), CONCAT_WS('',   `bio_storyline1`.`id`, '    ', `bio_storyline1`.`storyline_title`), '') /* Transcript A */" => "bio_storyline",
		"IF(    CHAR_LENGTH(`bio_storyline2`.`storyline`), CONCAT_WS('',   `bio_storyline2`.`storyline`, '   '), '') /* Token A */" => "bio_storytext",
		"IF(    CHAR_LENGTH(`hist_chr_scene1`.`id`), CONCAT_WS('',   `hist_chr_scene1`.`id`, '   '), '') /* Scene A */" => "sceneA",
		"IF(    CHAR_LENGTH(`bio_chr2`.`id`) || CHAR_LENGTH(`bio_chr2`.`character_name`), CONCAT_WS('',   `bio_chr2`.`id`, '   ', `bio_chr2`.`character_name`), '') /* Author B */" => "bio_chrB",
		"IF(    CHAR_LENGTH(`bio_story2`.`id`) || CHAR_LENGTH(`bio_story2`.`story_title`), CONCAT_WS('',   `bio_story2`.`id`, ' -  ', `bio_story2`.`story_title`), '') /* Author name B */" => "bio_storyB",
		"IF(    CHAR_LENGTH(`bio_storyline3`.`storyline_no`) || CHAR_LENGTH(`bio_storyline3`.`storyline_title`), CONCAT_WS('',   `bio_storyline3`.`storyline_no`, '   ', `bio_storyline3`.`storyline_title`), '') /* Bibliography B */" => "bio_storylineB",
		"IF(    CHAR_LENGTH(`bio_storyline4`.`storyline`), CONCAT_WS('',   `bio_storyline4`.`storyline`, '   '), '') /* Transcript B */" => "bio_storytextB",
		"`hist_encounter`.`type`" => "type",
		"`hist_encounter`.`conflicttype`" => "conflicttype",
		"`hist_encounter`.`story_scene`" => "story_scene",
		"`hist_encounter`.`nd_color`" => "nd_color",
		"`hist_encounter`.`nd_width`" => "nd_width",
		"`hist_encounter`.`nd_style`" => "nd_style",
		"`hist_encounter`.`nd_opacity`" => "nd_opacity",
		"`hist_encounter`.`nd_visibility`" => "nd_visibility",
		"`hist_encounter`.`lbl_lable`" => "lbl_lable",
		"`hist_encounter`.`lbl_color`" => "lbl_color",
		"`hist_encounter`.`lbl_size`" => "lbl_size",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['bio_chrA' => 'Author A', 'bio_storyA' => 'Bibliography A', 'bio_storyline' => 'Transcript A', 'bio_storytext' => 'Token A', 'sceneA' => 'Scene A', 'bio_chrB' => 'Author B', 'bio_storyB' => 'Author name B', 'bio_storylineB' => 'Bibliography B', 'bio_storytextB' => 'Transcript B', ];

	$x->QueryFrom = "`hist_encounter` LEFT JOIN `bio_chr` as bio_chr1 ON `bio_chr1`.`id`=`hist_encounter`.`bio_chrA` LEFT JOIN `bio_story` as bio_story1 ON `bio_story1`.`id`=`hist_encounter`.`bio_storyA` LEFT JOIN `bio_storyline` as bio_storyline1 ON `bio_storyline1`.`id`=`hist_encounter`.`bio_storyline` LEFT JOIN `bio_storyline` as bio_storyline2 ON `bio_storyline2`.`id`=`hist_encounter`.`bio_storytext` LEFT JOIN `hist_chr_scene` as hist_chr_scene1 ON `hist_chr_scene1`.`id`=`hist_encounter`.`sceneA` LEFT JOIN `bio_chr` as bio_chr2 ON `bio_chr2`.`id`=`hist_encounter`.`bio_chrB` LEFT JOIN `bio_story` as bio_story2 ON `bio_story2`.`id`=`hist_encounter`.`bio_storyB` LEFT JOIN `bio_storyline` as bio_storyline3 ON `bio_storyline3`.`id`=`hist_encounter`.`bio_storylineB` LEFT JOIN `bio_storyline` as bio_storyline4 ON `bio_storyline4`.`id`=`hist_encounter`.`bio_storytextB` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'hist_encounter_view.php';
	$x->RedirectAfterInsert = 'hist_encounter_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Historical events';
	$x->TableIcon = 'resources/table_icons/arrow_refresh.png';
	$x->PrimaryKey = '`hist_encounter`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Author A', 'Bibliography A', 'Transcript A', 'Token A', 'Scene A', 'Author B', 'Author name B', 'Bibliography B', 'Transcript B', 'Type', 'Conflicttype', 'Story_scene', 'Nd_color', 'Nd_width', 'Nd_style', 'Nd_opacity', 'Nd_visibility', 'Lbl_lable', 'Lbl_color', 'Lbl_size', ];
	$x->ColFieldName = ['id', 'bio_chrA', 'bio_storyA', 'bio_storyline', 'bio_storytext', 'sceneA', 'bio_chrB', 'bio_storyB', 'bio_storylineB', 'bio_storytextB', 'type', 'conflicttype', 'story_scene', 'nd_color', 'nd_width', 'nd_style', 'nd_opacity', 'nd_visibility', 'lbl_lable', 'lbl_color', 'lbl_size', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/hist_encounter_templateTV.html';
	$x->SelectedTemplate = 'templates/hist_encounter_templateTVS.html';
	$x->TemplateDV = 'templates/hist_encounter_templateDV.html';
	$x->TemplateDVP = 'templates/hist_encounter_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `hist_encounter`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='hist_encounter' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `hist_encounter`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='hist_encounter' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`hist_encounter`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: hist_encounter_init
	$render = true;
	if(function_exists('hist_encounter_init')) {
		$args = [];
		$render = hist_encounter_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: hist_encounter_header
	$headerCode = '';
	if(function_exists('hist_encounter_header')) {
		$args = [];
		$headerCode = hist_encounter_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: hist_encounter_footer
	$footerCode = '';
	if(function_exists('hist_encounter_footer')) {
		$args = [];
		$footerCode = hist_encounter_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
