<?php

// Data functions (insert, update, delete, form) for table hist_storyweaving_scenes

// This script and data application were generated by AppGini 5.94
// Download AppGini for free from https://bigprof.com/appgini/download/

function hist_storyweaving_scenes_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('hist_storyweaving_scenes');
	if(!$arrPerm['insert']) return false;

	$data = [
		'story' => Request::val('story', ''),
		'step' => Request::val('step', ''),
		'throughline' => Request::val('throughline', ''),
		'domain' => Request::val('domain', ''),
		'concern' => Request::val('concern', ''),
		'issue' => Request::val('issue', ''),
		'theme' => Request::val('theme', ''),
		'sequence' => Request::val('sequence', ''),
	];


	// hook: hist_storyweaving_scenes_before_insert
	if(function_exists('hist_storyweaving_scenes_before_insert')) {
		$args = [];
		if(!hist_storyweaving_scenes_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('hist_storyweaving_scenes', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	update_calc_fields('hist_storyweaving_scenes', $recID, calculated_fields()['hist_storyweaving_scenes']);

	// hook: hist_storyweaving_scenes_after_insert
	if(function_exists('hist_storyweaving_scenes_after_insert')) {
		$res = sql("SELECT * FROM `hist_storyweaving_scenes` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!hist_storyweaving_scenes_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('hist_storyweaving_scenes', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) hist_storyweaving_scenes_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function hist_storyweaving_scenes_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function hist_storyweaving_scenes_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('hist_storyweaving_scenes', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: hist_storyweaving_scenes_before_delete
	if(function_exists('hist_storyweaving_scenes_before_delete')) {
		$args = [];
		if(!hist_storyweaving_scenes_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: hist_storylines
	$res = sql("SELECT `id` FROM `hist_storyweaving_scenes` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `hist_storylines` WHERE `storyweaving_scene_no`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'hist_storylines', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'hist_storylines', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="button" value="' . $Translation['yes'] . '" onClick="window.location = \'hist_storyweaving_scenes_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="button" value="' . $Translation[ 'no'] . '" onClick="window.location = \'hist_storyweaving_scenes_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: hist_storylines
	$res = sql("SELECT `id` FROM `hist_storyweaving_scenes` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `hist_storylines` WHERE `storyweaving_scene`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'hist_storylines', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'hist_storylines', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="button" value="' . $Translation['yes'] . '" onClick="window.location = \'hist_storyweaving_scenes_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="button" value="' . $Translation[ 'no'] . '" onClick="window.location = \'hist_storyweaving_scenes_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: hist_storylines
	$res = sql("SELECT `id` FROM `hist_storyweaving_scenes` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `hist_storylines` WHERE `storyweaving_sequence`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'hist_storylines', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'hist_storylines', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="button" value="' . $Translation['yes'] . '" onClick="window.location = \'hist_storyweaving_scenes_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="button" value="' . $Translation[ 'no'] . '" onClick="window.location = \'hist_storyweaving_scenes_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: hist_storylines
	$res = sql("SELECT `id` FROM `hist_storyweaving_scenes` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `hist_storylines` WHERE `storyweaving_theme`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'hist_storylines', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'hist_storylines', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="button" value="' . $Translation['yes'] . '" onClick="window.location = \'hist_storyweaving_scenes_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="button" value="' . $Translation[ 'no'] . '" onClick="window.location = \'hist_storyweaving_scenes_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `hist_storyweaving_scenes` WHERE `id`='{$selected_id}'", $eo);

	// hook: hist_storyweaving_scenes_after_delete
	if(function_exists('hist_storyweaving_scenes_after_delete')) {
		$args = [];
		hist_storyweaving_scenes_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='hist_storyweaving_scenes' AND `pkValue`='{$selected_id}'", $eo);
}

function hist_storyweaving_scenes_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('hist_storyweaving_scenes', $selected_id, 'edit')) return false;

	$data = [
		'story' => Request::val('story', ''),
		'step' => Request::val('step', ''),
		'throughline' => Request::val('throughline', ''),
		'domain' => Request::val('domain', ''),
		'concern' => Request::val('concern', ''),
		'issue' => Request::val('issue', ''),
		'theme' => Request::val('theme', ''),
		'sequence' => Request::val('sequence', ''),
	];

	// get existing values
	$old_data = getRecord('hist_storyweaving_scenes', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: hist_storyweaving_scenes_before_update
	if(function_exists('hist_storyweaving_scenes_before_update')) {
		$args = ['old_data' => $old_data];
		if(!hist_storyweaving_scenes_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'hist_storyweaving_scenes', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="hist_storyweaving_scenes_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('hist_storyweaving_scenes', $data['selectedID'], calculated_fields()['hist_storyweaving_scenes']);

	// hook: hist_storyweaving_scenes_after_update
	if(function_exists('hist_storyweaving_scenes_after_update')) {
		$res = sql("SELECT * FROM `hist_storyweaving_scenes` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!hist_storyweaving_scenes_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='hist_storyweaving_scenes' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function hist_storyweaving_scenes_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm = getTablePermissions('hist_storyweaving_scenes');
	if(!$arrPerm['insert'] && $selected_id=='') { return ''; }
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_story = thisOr($_REQUEST['filterer_story'], '');
	$filterer_step = thisOr($_REQUEST['filterer_step'], '');
	$filterer_throughline = thisOr($_REQUEST['filterer_throughline'], '');
	$filterer_domain = thisOr($_REQUEST['filterer_domain'], '');
	$filterer_concern = thisOr($_REQUEST['filterer_concern'], '');
	$filterer_issue = thisOr($_REQUEST['filterer_issue'], '');
	$filterer_theme = thisOr($_REQUEST['filterer_theme'], '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: story
	$combo_story = new DataCombo;
	// combobox: step
	$combo_step = new DataCombo;
	// combobox: throughline
	$combo_throughline = new DataCombo;
	// combobox: domain
	$combo_domain = new DataCombo;
	// combobox: concern
	$combo_concern = new DataCombo;
	// combobox: issue
	$combo_issue = new DataCombo;
	// combobox: theme
	$combo_theme = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return '';

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='hist_storyweaving_scenes' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='hist_storyweaving_scenes' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return '';
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return '';

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `hist_storyweaving_scenes` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'hist_storyweaving_scenes_view.php', false);
		}
		$combo_story->SelectedData = $row['story'];
		$combo_step->SelectedData = $row['step'];
		$combo_throughline->SelectedData = $row['throughline'];
		$combo_domain->SelectedData = $row['domain'];
		$combo_concern->SelectedData = $row['concern'];
		$combo_issue->SelectedData = $row['issue'];
		$combo_theme->SelectedData = $row['theme'];
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input(datalist_db_encoding);
		$row = $hc->xss_clean($row); /* sanitize data */
	} else {
		$combo_story->SelectedData = $filterer_story;
		$combo_step->SelectedData = $filterer_step;
		$combo_throughline->SelectedData = $filterer_throughline;
		$combo_domain->SelectedData = $filterer_domain;
		$combo_concern->SelectedData = $filterer_concern;
		$combo_issue->SelectedData = $filterer_issue;
		$combo_theme->SelectedData = $filterer_theme;
	}
	$combo_story->HTML = '<span id="story-container' . $rnd1 . '"></span><input type="hidden" name="story" id="story' . $rnd1 . '" value="' . html_attr($combo_story->SelectedData) . '">';
	$combo_story->MatchText = '<span id="story-container-readonly' . $rnd1 . '"></span><input type="hidden" name="story" id="story' . $rnd1 . '" value="' . html_attr($combo_story->SelectedData) . '">';
	$combo_step->HTML = '<span id="step-container' . $rnd1 . '"></span><input type="hidden" name="step" id="step' . $rnd1 . '" value="' . html_attr($combo_step->SelectedData) . '">';
	$combo_step->MatchText = '<span id="step-container-readonly' . $rnd1 . '"></span><input type="hidden" name="step" id="step' . $rnd1 . '" value="' . html_attr($combo_step->SelectedData) . '">';
	$combo_throughline->HTML = '<span id="throughline-container' . $rnd1 . '"></span><input type="hidden" name="throughline" id="throughline' . $rnd1 . '" value="' . html_attr($combo_throughline->SelectedData) . '">';
	$combo_throughline->MatchText = '<span id="throughline-container-readonly' . $rnd1 . '"></span><input type="hidden" name="throughline" id="throughline' . $rnd1 . '" value="' . html_attr($combo_throughline->SelectedData) . '">';
	$combo_domain->HTML = '<span id="domain-container' . $rnd1 . '"></span><input type="hidden" name="domain" id="domain' . $rnd1 . '" value="' . html_attr($combo_domain->SelectedData) . '">';
	$combo_domain->MatchText = '<span id="domain-container-readonly' . $rnd1 . '"></span><input type="hidden" name="domain" id="domain' . $rnd1 . '" value="' . html_attr($combo_domain->SelectedData) . '">';
	$combo_concern->HTML = '<span id="concern-container' . $rnd1 . '"></span><input type="hidden" name="concern" id="concern' . $rnd1 . '" value="' . html_attr($combo_concern->SelectedData) . '">';
	$combo_concern->MatchText = '<span id="concern-container-readonly' . $rnd1 . '"></span><input type="hidden" name="concern" id="concern' . $rnd1 . '" value="' . html_attr($combo_concern->SelectedData) . '">';
	$combo_issue->HTML = '<span id="issue-container' . $rnd1 . '"></span><input type="hidden" name="issue" id="issue' . $rnd1 . '" value="' . html_attr($combo_issue->SelectedData) . '">';
	$combo_issue->MatchText = '<span id="issue-container-readonly' . $rnd1 . '"></span><input type="hidden" name="issue" id="issue' . $rnd1 . '" value="' . html_attr($combo_issue->SelectedData) . '">';
	$combo_theme->HTML = '<span id="theme-container' . $rnd1 . '"></span><input type="hidden" name="theme" id="theme' . $rnd1 . '" value="' . html_attr($combo_theme->SelectedData) . '">';
	$combo_theme->MatchText = '<span id="theme-container-readonly' . $rnd1 . '"></span><input type="hidden" name="theme" id="theme' . $rnd1 . '" value="' . html_attr($combo_theme->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_story__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['story'] : $filterer_story); ?>"};
		AppGini.current_step__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['step'] : $filterer_step); ?>"};
		AppGini.current_throughline__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['throughline'] : $filterer_throughline); ?>"};
		AppGini.current_domain__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['domain'] : $filterer_domain); ?>"};
		AppGini.current_concern__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['concern'] : $filterer_concern); ?>"};
		AppGini.current_issue__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['issue'] : $filterer_issue); ?>"};
		AppGini.current_theme__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['theme'] : $filterer_theme); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(story_reload__RAND__) == 'function') story_reload__RAND__();
				if(typeof(step_reload__RAND__) == 'function') step_reload__RAND__();
				if(typeof(throughline_reload__RAND__) == 'function') throughline_reload__RAND__();
				if(typeof(domain_reload__RAND__) == 'function') domain_reload__RAND__();
				if(typeof(concern_reload__RAND__) == 'function') concern_reload__RAND__();
				if(typeof(issue_reload__RAND__) == 'function') issue_reload__RAND__();
				if(typeof(theme_reload__RAND__) == 'function') theme_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function story_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#story-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_story__RAND__.value, t: 'hist_storyweaving_scenes', f: 'story' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="story"]').val(resp.results[0].id);
							$j('[id=story-container-readonly__RAND__]').html('<span id="story-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=hist_story_view_parent]').hide(); } else { $j('.btn[id=hist_story_view_parent]').show(); }


							if(typeof(story_update_autofills__RAND__) == 'function') story_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'hist_storyweaving_scenes', f: 'story' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_story__RAND__.value = e.added.id;
				AppGini.current_story__RAND__.text = e.added.text;
				$j('[name="story"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=hist_story_view_parent]').hide(); } else { $j('.btn[id=hist_story_view_parent]').show(); }


				if(typeof(story_update_autofills__RAND__) == 'function') story_update_autofills__RAND__();
			});

			if(!$j("#story-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_story__RAND__.value, t: 'hist_storyweaving_scenes', f: 'story' },
					success: function(resp) {
						$j('[name="story"]').val(resp.results[0].id);
						$j('[id=story-container-readonly__RAND__]').html('<span id="story-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=hist_story_view_parent]').hide(); } else { $j('.btn[id=hist_story_view_parent]').show(); }

						if(typeof(story_update_autofills__RAND__) == 'function') story_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_story__RAND__.value, t: 'hist_storyweaving_scenes', f: 'story' },
				success: function(resp) {
					$j('[id=story-container__RAND__], [id=story-container-readonly__RAND__]').html('<span id="story-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=hist_story_view_parent]').hide(); } else { $j('.btn[id=hist_story_view_parent]').show(); }

					if(typeof(story_update_autofills__RAND__) == 'function') story_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function step_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#step-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_step__RAND__.value, t: 'hist_storyweaving_scenes', f: 'step' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="step"]').val(resp.results[0].id);
							$j('[id=step-container-readonly__RAND__]').html('<span id="step-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_steps_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_steps_view_parent]').show(); }


							if(typeof(step_update_autofills__RAND__) == 'function') step_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'hist_storyweaving_scenes', f: 'step' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_step__RAND__.value = e.added.id;
				AppGini.current_step__RAND__.text = e.added.text;
				$j('[name="step"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_steps_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_steps_view_parent]').show(); }


				if(typeof(step_update_autofills__RAND__) == 'function') step_update_autofills__RAND__();
			});

			if(!$j("#step-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_step__RAND__.value, t: 'hist_storyweaving_scenes', f: 'step' },
					success: function(resp) {
						$j('[name="step"]').val(resp.results[0].id);
						$j('[id=step-container-readonly__RAND__]').html('<span id="step-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_steps_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_steps_view_parent]').show(); }

						if(typeof(step_update_autofills__RAND__) == 'function') step_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_step__RAND__.value, t: 'hist_storyweaving_scenes', f: 'step' },
				success: function(resp) {
					$j('[id=step-container__RAND__], [id=step-container-readonly__RAND__]').html('<span id="step-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_steps_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_steps_view_parent]').show(); }

					if(typeof(step_update_autofills__RAND__) == 'function') step_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function throughline_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#throughline-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_throughline__RAND__.value, t: 'hist_storyweaving_scenes', f: 'throughline' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="throughline"]').val(resp.results[0].id);
							$j('[id=throughline-container-readonly__RAND__]').html('<span id="throughline-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_throughline_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_throughline_view_parent]').show(); }


							if(typeof(throughline_update_autofills__RAND__) == 'function') throughline_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'hist_storyweaving_scenes', f: 'throughline' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_throughline__RAND__.value = e.added.id;
				AppGini.current_throughline__RAND__.text = e.added.text;
				$j('[name="throughline"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_throughline_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_throughline_view_parent]').show(); }


				if(typeof(throughline_update_autofills__RAND__) == 'function') throughline_update_autofills__RAND__();
			});

			if(!$j("#throughline-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_throughline__RAND__.value, t: 'hist_storyweaving_scenes', f: 'throughline' },
					success: function(resp) {
						$j('[name="throughline"]').val(resp.results[0].id);
						$j('[id=throughline-container-readonly__RAND__]').html('<span id="throughline-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_throughline_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_throughline_view_parent]').show(); }

						if(typeof(throughline_update_autofills__RAND__) == 'function') throughline_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_throughline__RAND__.value, t: 'hist_storyweaving_scenes', f: 'throughline' },
				success: function(resp) {
					$j('[id=throughline-container__RAND__], [id=throughline-container-readonly__RAND__]').html('<span id="throughline-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_throughline_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_throughline_view_parent]').show(); }

					if(typeof(throughline_update_autofills__RAND__) == 'function') throughline_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function domain_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#domain-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_domain__RAND__.value, t: 'hist_storyweaving_scenes', f: 'domain' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="domain"]').val(resp.results[0].id);
							$j('[id=domain-container-readonly__RAND__]').html('<span id="domain-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_domain_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_domain_view_parent]').show(); }


							if(typeof(domain_update_autofills__RAND__) == 'function') domain_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'hist_storyweaving_scenes', f: 'domain' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_domain__RAND__.value = e.added.id;
				AppGini.current_domain__RAND__.text = e.added.text;
				$j('[name="domain"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_domain_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_domain_view_parent]').show(); }


				if(typeof(domain_update_autofills__RAND__) == 'function') domain_update_autofills__RAND__();
			});

			if(!$j("#domain-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_domain__RAND__.value, t: 'hist_storyweaving_scenes', f: 'domain' },
					success: function(resp) {
						$j('[name="domain"]').val(resp.results[0].id);
						$j('[id=domain-container-readonly__RAND__]').html('<span id="domain-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_domain_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_domain_view_parent]').show(); }

						if(typeof(domain_update_autofills__RAND__) == 'function') domain_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_domain__RAND__.value, t: 'hist_storyweaving_scenes', f: 'domain' },
				success: function(resp) {
					$j('[id=domain-container__RAND__], [id=domain-container-readonly__RAND__]').html('<span id="domain-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_domain_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_domain_view_parent]').show(); }

					if(typeof(domain_update_autofills__RAND__) == 'function') domain_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function concern_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#concern-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_concern__RAND__.value, t: 'hist_storyweaving_scenes', f: 'concern' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="concern"]').val(resp.results[0].id);
							$j('[id=concern-container-readonly__RAND__]').html('<span id="concern-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_concern_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_concern_view_parent]').show(); }


							if(typeof(concern_update_autofills__RAND__) == 'function') concern_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'hist_storyweaving_scenes', f: 'concern' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_concern__RAND__.value = e.added.id;
				AppGini.current_concern__RAND__.text = e.added.text;
				$j('[name="concern"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_concern_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_concern_view_parent]').show(); }


				if(typeof(concern_update_autofills__RAND__) == 'function') concern_update_autofills__RAND__();
			});

			if(!$j("#concern-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_concern__RAND__.value, t: 'hist_storyweaving_scenes', f: 'concern' },
					success: function(resp) {
						$j('[name="concern"]').val(resp.results[0].id);
						$j('[id=concern-container-readonly__RAND__]').html('<span id="concern-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_concern_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_concern_view_parent]').show(); }

						if(typeof(concern_update_autofills__RAND__) == 'function') concern_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_concern__RAND__.value, t: 'hist_storyweaving_scenes', f: 'concern' },
				success: function(resp) {
					$j('[id=concern-container__RAND__], [id=concern-container-readonly__RAND__]').html('<span id="concern-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_concern_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_concern_view_parent]').show(); }

					if(typeof(concern_update_autofills__RAND__) == 'function') concern_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function issue_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#issue-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_issue__RAND__.value, t: 'hist_storyweaving_scenes', f: 'issue' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="issue"]').val(resp.results[0].id);
							$j('[id=issue-container-readonly__RAND__]').html('<span id="issue-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_issue_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_issue_view_parent]').show(); }


							if(typeof(issue_update_autofills__RAND__) == 'function') issue_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'hist_storyweaving_scenes', f: 'issue' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_issue__RAND__.value = e.added.id;
				AppGini.current_issue__RAND__.text = e.added.text;
				$j('[name="issue"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_issue_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_issue_view_parent]').show(); }


				if(typeof(issue_update_autofills__RAND__) == 'function') issue_update_autofills__RAND__();
			});

			if(!$j("#issue-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_issue__RAND__.value, t: 'hist_storyweaving_scenes', f: 'issue' },
					success: function(resp) {
						$j('[name="issue"]').val(resp.results[0].id);
						$j('[id=issue-container-readonly__RAND__]').html('<span id="issue-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_issue_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_issue_view_parent]').show(); }

						if(typeof(issue_update_autofills__RAND__) == 'function') issue_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_issue__RAND__.value, t: 'hist_storyweaving_scenes', f: 'issue' },
				success: function(resp) {
					$j('[id=issue-container__RAND__], [id=issue-container-readonly__RAND__]').html('<span id="issue-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_issue_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_issue_view_parent]').show(); }

					if(typeof(issue_update_autofills__RAND__) == 'function') issue_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function theme_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#theme-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_theme__RAND__.value, t: 'hist_storyweaving_scenes', f: 'theme' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="theme"]').val(resp.results[0].id);
							$j('[id=theme-container-readonly__RAND__]').html('<span id="theme-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_themes_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_themes_view_parent]').show(); }


							if(typeof(theme_update_autofills__RAND__) == 'function') theme_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'hist_storyweaving_scenes', f: 'theme' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_theme__RAND__.value = e.added.id;
				AppGini.current_theme__RAND__.text = e.added.text;
				$j('[name="theme"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_themes_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_themes_view_parent]').show(); }


				if(typeof(theme_update_autofills__RAND__) == 'function') theme_update_autofills__RAND__();
			});

			if(!$j("#theme-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_theme__RAND__.value, t: 'hist_storyweaving_scenes', f: 'theme' },
					success: function(resp) {
						$j('[name="theme"]').val(resp.results[0].id);
						$j('[id=theme-container-readonly__RAND__]').html('<span id="theme-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_themes_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_themes_view_parent]').show(); }

						if(typeof(theme_update_autofills__RAND__) == 'function') theme_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_theme__RAND__.value, t: 'hist_storyweaving_scenes', f: 'theme' },
				success: function(resp) {
					$j('[id=theme-container__RAND__], [id=theme-container-readonly__RAND__]').html('<span id="theme-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=class_dramatica_themes_view_parent]').hide(); } else { $j('.btn[id=class_dramatica_themes_view_parent]').show(); }

					if(typeof(theme_update_autofills__RAND__) == 'function') theme_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/hist_storyweaving_scenes_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/hist_storyweaving_scenes_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return hist_storyweaving_scenes_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return hist_storyweaving_scenes_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return hist_storyweaving_scenes_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly .= "\tjQuery('#story').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#story_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#step').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#step_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#throughline').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#throughline_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#domain').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#domain_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#concern').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#concern_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#issue').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#issue_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#theme').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#theme_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#sequence').replaceWith('<div class=\"form-control-static\" id=\"sequence\">' + (jQuery('#sequence').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(story)%%>', $combo_story->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(story)%%>', $combo_story->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(story)%%>', urlencode($combo_story->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(step)%%>', $combo_step->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(step)%%>', $combo_step->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(step)%%>', urlencode($combo_step->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(throughline)%%>', $combo_throughline->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(throughline)%%>', $combo_throughline->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(throughline)%%>', urlencode($combo_throughline->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(domain)%%>', $combo_domain->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(domain)%%>', $combo_domain->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(domain)%%>', urlencode($combo_domain->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(concern)%%>', $combo_concern->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(concern)%%>', $combo_concern->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(concern)%%>', urlencode($combo_concern->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(issue)%%>', $combo_issue->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(issue)%%>', $combo_issue->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(issue)%%>', urlencode($combo_issue->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(theme)%%>', $combo_theme->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(theme)%%>', $combo_theme->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(theme)%%>', urlencode($combo_theme->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('story' => array('hist_story', 'Story'), 'step' => array('class_dramatica_steps', 'Step'), 'throughline' => array('class_dramatica_throughline', 'Throughline'), 'domain' => array('class_dramatica_domain', 'Domain'), 'concern' => array('class_dramatica_concern', 'Concern'), 'issue' => array('class_dramatica_issue', 'Issue'), 'theme' => array('class_dramatica_themes', 'Theme'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(story)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(step)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(throughline)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(domain)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(concern)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(issue)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(theme)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(sequence)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(story)%%>', safe_html($urow['story']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(story)%%>', html_attr($row['story']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(story)%%>', urlencode($urow['story']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(step)%%>', safe_html($urow['step']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(step)%%>', html_attr($row['step']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(step)%%>', urlencode($urow['step']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(throughline)%%>', safe_html($urow['throughline']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(throughline)%%>', html_attr($row['throughline']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(throughline)%%>', urlencode($urow['throughline']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(domain)%%>', safe_html($urow['domain']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(domain)%%>', html_attr($row['domain']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(domain)%%>', urlencode($urow['domain']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(concern)%%>', safe_html($urow['concern']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(concern)%%>', html_attr($row['concern']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(concern)%%>', urlencode($urow['concern']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(issue)%%>', safe_html($urow['issue']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(issue)%%>', html_attr($row['issue']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(issue)%%>', urlencode($urow['issue']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(theme)%%>', safe_html($urow['theme']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(theme)%%>', html_attr($row['theme']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(theme)%%>', urlencode($urow['theme']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(sequence)%%>', safe_html($urow['sequence']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(sequence)%%>', html_attr($row['sequence']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sequence)%%>', urlencode($urow['sequence']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(story)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(story)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(step)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(step)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(throughline)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(throughline)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(domain)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(domain)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(concern)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(concern)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(issue)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(issue)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(theme)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(theme)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(sequence)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sequence)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('hist_storyweaving_scenes');
	if($selected_id) {
		$jdata = get_joined_record('hist_storyweaving_scenes', $selected_id);
		if($jdata === false) $jdata = get_defaults('hist_storyweaving_scenes');
		$rdata = $row;
	}
	$templateCode .= loadView('hist_storyweaving_scenes-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: hist_storyweaving_scenes_dv
	if(function_exists('hist_storyweaving_scenes_dv')) {
		$args=[];
		hist_storyweaving_scenes_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}